root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "templ generate && tailwindcss -i ./view/css/app.css -o ./public/styles.css && go build -o ./tmp/main ."
	
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "uploads"]
  exclude_file = []
  exclude_unchanged = false
  exclude_regex = [".*_templ.go"]
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true